task: semantic_segmentation

dataset_parameters:
  input_directory: train_images
  target_directory: rle
  mask_format: rle

model_parameters:
  model_class: Unet
  model_args:
    encoder_name: efficientnet-b0
    encoder_depth: 5
    encoder_weights: imagenet
    decoder_use_batchnorm: True
    decoder_channels: [256, 128, 64, 32, 16]
    decoder_attention_type: null
    in_channels: 3
    classes: 1
    activation: null
    aux_params: null
  model_checkpoint_path: null

training_parameters:
  folds: [fold1]#, fold2, fold3, fold4, fold5]
  loss_function: WeightedSegmentationLoss
  loss_args:
    distribution_based_loss_function: SoftBCEWithLogitsLoss
    distribution_based_loss_function_args: {}
    distribution_based_loss_function_weight: 0.5
    region_based_loss_function: TverskyLoss
    region_based_loss_function_args:
      mode: binary
      log_loss: False
      from_logits: True
      smooth: 0.0
      alpha: 0.5
      beta: 0.5
      gamma: 1.0
    region_based_loss_function_weight: 0.5
  optimizer: Adam
  optimizer_args:
    lr: 0.001
    betas: [0.9, 0.999]
    weight_decay: 0.0
  lr_scheduler: StepLR
  lr_scheduler_args:
    step_size: 200
    gamma: 0.5
    last_epoch: -1
  epochs: 250
  early_stopping_patience: 10
  training_batch_size: 8
  test_batch_size: 16
  num_workers: 4
  random_state: 42
  deterministic_cudnn: False
  device: cuda

transform_parameters:
  resize_height: 768
  resize_width: 768
  horizontal_flip_probability: 0.5
  vertical_flip_probability: 0.5
  random_rotate_90_probability: 0.25
  normalize_mean: [0.8461123334500709, 0.8181881670128927, 0.8396328177126106]
  normalize_std: [0.15422885530869604, 0.19460989079464583, 0.16390648194643512]
  normalize_max_pixel_value: 255

inference_parameters:
  folds: [fold1, fold2, fold3, fold4, fold5]
  label_threshold_range: [0.5]
  label_thresholds:
    kidney: 0.5
    prostate: 0.5
    largeintestine: 0.5
    spleen: 0.5
    lung: 0.5

persistence_parameters:
  name: unet_semantic_segmentation_raw
  save_models: True
  save_visualizations: True
