task: semantic_segmentation

dataset_parameters:
  inputs: image_filename
  targets: rle
  mask_format: rle
  hubmap_kidney_segmentation_sample_count: 50
  mask_area_range: [100000, 500000]
  crop_black_border: False
  crop_background: False

model_parameters:
  model_module: smp
  model_class: Unet
  model_args:
    encoder_name: efficientnet-b1
    encoder_depth: 5
    encoder_weights: imagenet
    decoder_use_batchnorm: True
    decoder_channels: [256, 128, 64, 32, 16]
    decoder_attention_type: null
    in_channels: 3
    classes: 1
    activation: null
    aux_params: null
  model_checkpoint_path: null

training_parameters:
  folds: [fold1]
  loss_function: WeightedSegmentationLoss
  loss_args:
    distribution_based_loss_function: SoftBCEWithLogitsLoss
    distribution_based_loss_function_args: {}
    distribution_based_loss_function_weight: 0.5
    region_based_loss_function: TverskyLoss
    region_based_loss_function_args:
      mode: binary
      log_loss: False
      from_logits: True
      smooth: 0.0
      alpha: 0.5
      beta: 0.5
      gamma: 1.0
    region_based_loss_function_weight: 0.5
  optimizer: Adam
  optimizer_args:
    lr: 0.001
    betas: [0.9, 0.999]
    weight_decay: 0.0
  lr_scheduler: StepLR
  lr_scheduler_args:
    step_size: 1500
    gamma: 0.5
    last_epoch: -1
  epochs: 250
  early_stopping_patience: 10
  training_batch_size: 8
  test_batch_size: 16
  num_workers: 4
  random_state: 42
  deterministic_cudnn: False
  device: cuda

transform_parameters:
  resize_height: 768
  resize_width: 768
  resize_scale: [0.25, 0.95]
  resize_ratio: [0.7, 1.3]
  horizontal_flip_probability: 0.5
  vertical_flip_probability: 0.5
  random_rotate_90_probability: 0.25
  brightness: 0.3
  contrast: 0.3
  saturation: 0.3
  hue: 0.3
  color_jitter_probability: 0.5
  r_shift_limit: 25
  g_shift_limit: 25
  b_shift_limit: 25
  rgb_shift_probability: 0.5
  channel_shuffle_probability: 0.5
  rgb_augmentation_probability: 0.25
  normalize_mean: [0.6864609437833393, 0.5534345620480285, 0.7187172954823893]
  normalize_std: [0.18722252278327903, 0.26679424300841664, 0.16788759187664415]
  normalize_max_pixel_value: 255

inference_parameters:
  folds: [fold1]
  label_threshold_range: [0.5]
  label_thresholds:
    kidney: 0.5
    prostate: 0.5
    largeintestine: 0.5
    spleen: 0.5
    lung: 0.5

persistence_parameters:
  name: unet_semantic_segmentation_raw
  visualize_epoch_predictions: True
  visualize_final_predictions: True
  evaluate_final_predictions: True
  visualize_learning_curve: True
  visualize_training_scores: True
  save_models: True
